include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for NYN 802.1x Authentication Client
LUCI_DEPENDS:=+zzz +luci-base

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
